### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by mzhukovs** [rouanw/npm-audit-helper#3]
After running `npm audit --json | npm-audit-helper`
on a project with a lot of vulnerabilities (perhaps this is the issue), I get:

> SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at help (C:\Users\A12945\AppData\Roaming\npm\node_modules\npm-audit-helper\lib\help.js:57:33)

This is the metadata from npm audit --json result:
```
  "metadata": {
    "vulnerabilities": {
      "info": 0,
      "low": 1329,
      "moderate": 0,
      "high": 2,
      "critical": 0
    },
    "dependencies": 15,
    "devDependencies": 1393,
    "optionalDependencies": 101,
    "totalDependencies": 1408
  },
```

**Comment by rouanw** [comment]
Thanks for reporting @mzhukovs.

Some questions to help me debug:

1. What is the output of `npm --version`?
2. What is the output of `node --version`?
3. Do you get the error when you run `npm --loglevel silent audit --json | npm-audit-helper`?
4. Do you get the error when you run `npm audit --json | npx npm-audit-helper`?
5. When you run `npm audit --json` do you notice any output before or after the JSON?

**Comment by mzhukovs** [comment]
Apparently this is a powrshell related problem , works fine in cmd prompt
