### ISSUE TITLE
support yarn

### ISSUE THREAD

**Issue by SinaKarimi7** [rouanw/npm-audit-helper#7]
Hello @rouanw, Is there any way to use this library with yarn, too?

**Comment by rouanw** [comment]
@SinaKarimi7 The output of `yarn audit --json` has a completely different structure to `npm audit --json` which `npm-audit-helper` used.

That means there's no current way to use `npm-audit-helper` with yarn. One workaround would be to run:

```sh
npm audit --json | npx npm-audit-helper
```

To get the vulnerability data in the npm format. You can then fix vulnerabilities using `yarn add` etc. When you're done you'll want to delete the `package-lock.json` npm created and run `yarn install` to make sure your node modules are as yarn wants them.
